<?xml version="1.0" encoding="utf-8"?><Database Name="FirebasePushMessage" Class="MTokenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-60RN6QI\STEALEROFSOULS;Initial Catalog=FirebasePushMessage;Persist Security Info=True;User ID=nguyenxuanhoi2903" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FirebasePushMessageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FirebaseCloud" Member="FirebaseClouds">
    <Type Name="FirebaseCloud">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>